apiVersion: cluster.k8s.io/v1alpha1
kind: MachineList
items:
# Master machine
- apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    generateName: my-exoscale-master-
    labels:
      cluster.k8s.io/cluster-name: my-exoscale-cluster
      set: master
  spec:
    providerSpec:
      value:
        apiVersion: exoscale.cluster.k8s.io/v1alpha1
        kind: ExoscaleMachineProviderSpec
        zone: de-fra-1
        # if template not provisioned we recommend only ubuntu
        template: "Linux Ubuntu 18.04 LTS 64-bit"
        # if you provide a template already provisioned (docker, kubelet, kubeadm, kubectl),
        # set value to "true"
        provisioned: false
        type: medium
        disk: 50
    versions:
      kubelet: 1.14.0
      controlPlane: 1.14.0
# Worker machine
- apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    generateName: my-exoscale-node-
    labels:
      cluster.k8s.io/cluster-name: my-exoscale-cluster
      set: node
  spec:
    providerSpec:
      value:
        apiVersion: exoscale.cluster.k8s.io/v1alpha1
        kind: ExoscaleMachineProviderSpec
        zone: de-fra-1
        template: "Linux Ubuntu 18.04 LTS 64-bit"
         # if template not provisioned we recommend only ubuntu
        template: "Linux Ubuntu 18.04 LTS 64-bit"
        # if you provide a template already provisioned (docker, kubelet, kubeadm, kubectl),
        # set value to "true"
        provisioned: false
        type: medium
        disk: 50
    versions:
      kubelet: 1.14.0
