apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: exoscaleclusterproviderstatuses.exoscale.cluster.k8s.io
spec:
  group: exoscale.cluster.k8s.io
  names:
    kind: ExoscaleClusterProviderStatus
    plural: exoscaleclusterproviderstatuses
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            sshkey:
              type: string
            zone:
              type: string
          required:
          - zone
          - sshkey
          type: object
        status:
          properties:
            sshkey:
              type: string
            zone:
              type: string
          required:
          - zone
          - sshkey
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
