apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: controllers
spec:
  template:
    spec:
      containers:
      - name: exoscale-controller
        image: exoscale/cluster-api-provider-exoscale-controller:latest
